name: Deploy docs

on:
  push:
    branches: [ 386-Build-TriBITS-Documentation-with-Sphinx-and-ReadTheDocs ]

jobs:
  build_and_deploy_docs:

    runs-on: ubuntu-latest
    env:
      working-directory: ./tribits/doc/sphinx

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python2 -m pip install --upgrade pip
          pip2 install sphinx sphinx-rtd-theme
          python3 -m pip install --upgrade pip
          pip3 install sphinx sphinx-rtd-theme
      - name: Build documentation
        working-directory: ${{env.working-directory}}
        run: python3 sphinx_rst_generator.py
      - name: Generate html output
        working-directory: ${{env.working-directory}}
        run: make html